version: '3'
services:
  strapi:
    image: strapi/strapi
    # command: strapi develop --watch-admin
    environment:
      DATABASE_CLIENT: mongo
      ADMIN_URL: ${ADMIN_URL}
      DATABASE_SSL: ${DATABASE_SSL}
      EXPO_ACCESS_TOKEN: ${EXPO_ACCESS_TOKEN}
      MONGO_DSN: ${MONGO_DSN}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'