version: '3'
services:
  strapi:
    image: strapi/strapi
    # command: strapi develop --watch-admin
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: swallow
      DATABASE_HOST: docker.for.mac.host.internal
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'